'use strict';

const NAXOS='https://raw.githubusercontent.com/DDRNFinch/Naxosv2/main/';
const SOURCE=NAXOS+'data/evidence-packs-source.json';
const state={view:'home',course:null,packs:[],profile:{name:'',courseKey:'ST0095'},evidence:{},otj:[]};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function load(){
  const saved=JSON.parse(localStorage.getItem('walsall-state')||'null');
  if(saved){Object.assign(state,saved);state.profile=saved.profile||state.profile;state.evidence=saved.evidence||{};state.otj=saved.otj||[]}
  try{await loadCourse(state.profile.courseKey||'ST0095')}catch(e){console.error(e);$('#app').innerHTML=`<div class="page"><div class="card"><h2>Course could not load</h2><p class="muted">The app could not read the Naxosv2 course pack.</p><pre>${esc(e.stack||e)}</pre></div></div>`;return}
  render();
}
async function loadCourse(key){
  const source=await fetch(SOURCE,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Could not load Naxos source');return r.json()});
  const cfg=source.courses[key]; if(!cfg)throw Error('Course not found in Naxosv2: '+key);
  if(cfg.type!=='standard-main-packs')throw Error('This first Walsall build supports standard learner packs.');
  const packs=await fetch(NAXOS+'data/standards/'+key+'/main-packs.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Could not load '+key+' packs');return r.json()});
  state.course={key,config:cfg,metadata:packs};state.packs=packs.packs||[];state.profile.courseKey=key;save();
  $('#courseLabel').textContent=key+' · '+state.packs.length+' packs';
}
function save(){localStorage.setItem('walsall-state',JSON.stringify(state));}
function pct(pack){const e=state.evidence[pack.id]||{photos:[],statement:''};const photos=Math.min((e.photos||[]).length,pack.capture.length);const statement=(e.statement||'').trim().length>=100?1:0;return Math.round(((photos/pack.capture.length)*80)+(statement*20));}
function status(pack){const p=pct(pack);return p>=100?'Complete':p?'In progress':'Not started'}
function render(){
  document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));
  if(state.view==='home')renderHome(); else if(state.view==='packs')renderPacks(); else if(state.view==='otj')renderOTJ(); else renderProfile();
}
function renderHome(){const done=state.packs.filter(p=>pct(p)>=100).length;const hours=state.otj.reduce((a,b)=>a+Number(b.hours||0),0);$('#app').innerHTML=`<div class="page"><section class="hero"><h1>${esc(state.profile.name||'Your evidence portfolio')}</h1><p>${esc(state.course?.key||'Course')} · ${done}/${state.packs.length} packs complete</p></section><div class="grid"><div class="card"><h3>Evidence packs</h3><strong>${done}/${state.packs.length}</strong><div class="progress"><i style="width:${state.packs.length?done/state.packs.length*100:0}%"></i></div><button class="btn primary full" onclick="go('packs')">Continue packs</button></div><div class="card"><h3>Off-the-job</h3><strong>${hours.toFixed(1)} hours</strong><p class="muted">${state.otj.length} entries</p><button class="btn full" onclick="go('otj')">Open OTJ</button></div></div><div class="card stack" style="margin-top:12px"><h3>How it works</h3><p class="muted">Follow each pack, take the requested photos, write your statement, then download the completed pack as a PDF.</p></div></div>`}
function renderPacks(){const html=state.packs.map((p,i)=>`<div class="card pack" onclick="openPack(${i})"><div class="pack-num">${String(i+1).padStart(2,'0')}</div><div style="flex:1"><h3>${esc(p.title)}</h3><p class="muted">${esc(p.summary)}</p><div class="status">${status(p)} · ${pct(p)}%</div><div class="progress"><i style="width:${pct(p)}%"></i></div></div></div>`).join('');$('#app').innerHTML=`<div class="page"><div class="page-head"><h1>Evidence packs</h1><p class="muted">Follow the Naxosv2 packs in order and build your evidence.</p></div><div class="stack">${html}</div></div>`}
function openPack(i){const p=state.packs[i],e=state.evidence[p.id]||{photos:[],statement:''};state.currentPack=i;save();$('#app').innerHTML=`<div class="page"><button class="btn" onclick="go('packs')">← All packs</button><div class="card" style="margin-top:12px"><div class="status">PACK ${String(i+1).padStart(2,'0')}</div><h1>${esc(p.title)}</h1><p class="muted">${esc(p.summary)}</p><h3>What to capture</h3><ul class="checklist">${p.capture.map((x,n)=>`<li><span class="${e.photos[n]?'tick':''}">${e.photos[n]?'✓':'○'}</span> ${esc(x)}</li>`).join('')}</ul></div><div class="card stack" style="margin-top:12px"><h3>Take your photos</h3><p class="muted">Use one photo for each requested item. You can retake any photo.</p><div class="photo-grid">${p.capture.map((prompt,n)=>photoBox(p.id,n,prompt,e.photos[n])).join('')}</div></div><div class="card stack" style="margin-top:12px"><h3>Your statement</h3><p class="muted">Explain what you did, how you did it and how you checked the finished work. Minimum 100 words.</p><textarea id="statement" placeholder="Write your statement here…" oninput="saveStatement('${p.id}',this.value)">${esc(e.statement||'')}</textarea><div class="status"><span id="wordCount">${wordCount(e.statement||'')}</span> words · minimum 100</div></div><div class="card stack" style="margin-top:12px"><h3>Mapped KSBs</h3><p class="muted">${(p.primaryKSBs||[]).map(esc).join(' · ')}</p><button class="btn green full" ${pct(p)<100?'disabled':''} onclick="downloadPack(${i})">Download completed pack PDF</button></div></div>`}
function photoBox(id,n,prompt,data){return `<div><label class="photo-box">${data?.data?`<img src="${data.data}" alt="${esc(prompt)}"><button onclick="event.preventDefault();removePhoto('${id}',${n})">×</button>`:`<input type="file" accept="image/*" capture="environment" style="position:absolute;inset:0;opacity:0;cursor:pointer" onchange="addPhoto(event,'${id}',${n})"> <div style="padding:18px;text-align:center"><strong>+ Photo</strong><div class="prompt">${esc(prompt)}</div></div>`}</label></div>`}
function wordCount(s){return s.trim()?s.trim().split(/\s+/).length:0}
function saveStatement(id,v){state.evidence[id]=state.evidence[id]||{photos:[],statement:''};state.evidence[id].statement=v;save();const w=$('#wordCount');if(w)w.textContent=wordCount(v)}
async function addPhoto(ev,id,n){const file=ev.target.files?.[0];if(!file)return;const data=await resizeImage(file,1400);state.evidence[id]=state.evidence[id]||{photos:[],statement:''};state.evidence[id].photos=state.evidence[id].photos||[];state.evidence[id].photos[n]={data,name:file.name};save();openPack(state.currentPack)}
function removePhoto(id,n){const e=state.evidence[id];if(!e)return;e.photos.splice(n,1);save();openPack(state.currentPack)}
function resizeImage(file,max){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const scale=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function renderOTJ(){const total=state.otj.reduce((a,b)=>a+Number(b.hours||0),0);const rows=state.otj.map((x,i)=>`<div class="card"><div style="display:flex;justify-content:space-between"><strong>${esc(x.date)}</strong><strong>${Number(x.hours).toFixed(1)}h</strong></div><p>${esc(x.activity)}</p><p class="muted">${esc(x.learning)}</p><button class="btn" onclick="deleteOTJ(${i})">Delete</button></div>`).join('');$('#app').innerHTML=`<div class="page"><div class="hero"><h1>Off-the-job training</h1><p>${total.toFixed(1)} hours recorded</p></div><div class="card stack"><h3>Add OTJ entry</h3><input class="input" id="otjDate" type="date" value="${new Date().toISOString().slice(0,10)}"><input class="input" id="otjHours" type="number" min="0.25" step="0.25" placeholder="Hours"><input class="input" id="otjActivity" placeholder="What did you do?"><textarea id="otjLearning" placeholder="What did you learn?"></textarea><button class="btn primary full" onclick="addOTJ()">Save OTJ entry</button></div><div class="stack" style="margin-top:12px">${rows||'<div class="card muted">No OTJ entries yet.</div>'}</div><button class="btn green full" style="margin-top:12px" ${state.otj.length?'':'disabled'} onclick="downloadOTJ()">Download collated OTJ PDF</button></div>`}
function addOTJ(){const date=$('#otjDate').value,hours=Number($('#otjHours').value),activity=$('#otjActivity').value.trim(),learning=$('#otjLearning').value.trim();if(!date||!hours||!activity){toast('Enter date, hours and activity');return}state.otj.push({date,hours,activity,learning});state.otj.sort((a,b)=>a.date.localeCompare(b.date));save();renderOTJ();toast('OTJ entry saved')}
function deleteOTJ(i){state.otj.splice(i,1);save();renderOTJ()}
function renderProfile(){const source=state.course?.config?.courses||{};$('#app').innerHTML=`<div class="page"><div class="card stack"><h1>Profile</h1><label>Name<input class="input" id="name" value="${esc(state.profile.name)}" placeholder="Your name"></label><label>Course<select class="input" id="course"><option value="${esc(state.profile.courseKey)}">${esc(state.profile.courseKey)}</option></select></label><button class="btn primary full" onclick="saveProfile()">Save profile</button><p class="muted">Course packs are read directly from Naxosv2. The learner cannot change the pack content.</p></div></div>`}
function saveProfile(){state.profile.name=$('#name').value.trim();save();renderHome();toast('Profile saved')}
function go(v){state.view=v;render()}
async function downloadPack(i){const p=state.packs[i],e=state.evidence[p.id];if(pct(p)<100){toast('Complete the photos and statement first');return}const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});let y=18;doc.setFontSize(20);doc.text('Evidence Pack',15,y);y+=10;doc.setFontSize(16);doc.text(p.title,15,y);y+=8;doc.setFontSize(10);doc.text(`Learner: ${state.profile.name||'Not entered'}`,15,y);y+=6;doc.text(`Course: ${state.profile.courseKey}`,15,y);y+=9;doc.setFontSize(11);doc.text('Pack summary',15,y);y+=6;y=writeWrapped(doc,p.summary,15,y,180,5);y+=5;doc.text('Evidence photographs',15,y);y+=7;for(let n=0;n<p.capture.length;n++){const ph=e.photos[n];if(!ph?.data)continue;if(y>245){doc.addPage();y=18}doc.setFontSize(10);doc.text(`${n+1}. ${p.capture[n]}`,15,y);y+=4;doc.addImage(ph.data,'JPEG',15,y,80,55);y+=62}doc.addPage();y=18;doc.setFontSize(14);doc.text('Learner statement',15,y);y+=8;doc.setFontSize(10);y=writeWrapped(doc,e.statement,15,y,180,5);y+=8;doc.setFontSize(12);doc.text('Mapped KSBs',15,y);y+=6;doc.setFontSize(10);y=writeWrapped(doc,(p.primaryKSBs||[]).join(' · '),15,y,180,5);y+=10;doc.setFontSize(9);doc.text('Generated from Naxosv2 learner pack data.',15,y);doc.save(`${safe(p.title)} - ${safe(state.profile.name||'Learner')}.pdf`);}
function downloadOTJ(){const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});let y=18;doc.setFontSize(20);doc.text('Off-the-job training record',15,y);y+=9;doc.setFontSize(10);doc.text(`Learner: ${state.profile.name||'Not entered'}`,15,y);y+=6;doc.text(`Course: ${state.profile.courseKey}`,15,y);y+=6;const total=state.otj.reduce((a,b)=>a+Number(b.hours||0),0);doc.text(`Total hours: ${total.toFixed(1)}`,15,y);y+=10;state.otj.forEach((x,i)=>{if(y>260){doc.addPage();y=18}doc.setFontSize(11);doc.text(`${x.date} — ${Number(x.hours).toFixed(1)} hours`,15,y);y+=6;doc.setFontSize(10);y=writeWrapped(doc,x.activity,15,y,180,5);if(x.learning){y+=2;y=writeWrapped(doc,'Learning: '+x.learning,15,y,180,5)}y+=6});doc.save(`${safe(state.profile.name||'Learner')} - Off the Job Training.pdf`)}
function writeWrapped(doc,text,x,y,width,line){const lines=doc.splitTextToSize(String(text||''),width);doc.text(lines,x,y);return y+(lines.length*line)}
function safe(s){return String(s||'').replace(/[^a-z0-9 _-]/gi,'').trim()||'Evidence'}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$('#profileBtn').addEventListener('click',()=>go('profile'));load();
window.go=go;window.openPack=openPack;window.addPhoto=addPhoto;window.removePhoto=removePhoto;window.saveStatement=saveStatement;window.downloadPack=downloadPack;window.addOTJ=addOTJ;window.deleteOTJ=deleteOTJ;window.downloadOTJ=downloadOTJ;window.saveProfile=saveProfile;
