'use strict';

const NAXOS='https://raw.githubusercontent.com/DDRNFinch/Naxosv2/main/';
const SOURCE=NAXOS+'data/evidence-packs-source.json';
const state={view:'home',course:null,packs:[],courses:{},profile:{name:'',courseKey:'ST0095'},evidence:{},otj:[],currentPack:0};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('walsall-evidence',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function photoPut(key,value){const db=await dbPromise;return new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(value,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function photoGet(key){const db=await dbPromise;return new Promise((res,rej)=>{const r=db.transaction('photos').objectStore('photos').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function photoDelete(key){const db=await dbPromise;return new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function photoKey(id,n){return id+'::'+n}
function save(){localStorage.setItem('walsall-state',JSON.stringify(state))}
function formatUKDate(value){if(!value)return'';const d=value instanceof Date?value:new Date(value+'T00:00:00');if(Number.isNaN(d.getTime()))return String(value);return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()}
function todayISO(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function nowUK(){return formatUKDate(todayISO())}
function wordCount(s){return s.trim()?s.trim().split(/\s+/).length:0}
function pct(pack){const e=state.evidence[pack.id]||{photos:[],statement:'',signature:''};const photos=Math.min((e.photos||[]).filter(Boolean).length,pack.capture.length);const statement=(e.statement||'').trim().length>=100?1:0;return Math.round((photos/pack.capture.length)*80+statement*20)}
function status(pack){const p=pct(pack);return p>=100?'Complete':p?'In progress':'Not started'}

async function load(){try{const saved=JSON.parse(localStorage.getItem('walsall-state')||'null');if(saved){Object.assign(state,saved);state.profile=saved.profile||state.profile;state.evidence=saved.evidence||{};state.otj=saved.otj||[];state.currentPack=saved.currentPack||0}}catch(e){console.warn('Saved data reset',e)}try{await loadCourse(state.profile.courseKey||'ST0095');render()}catch(e){console.error(e);$('#app').innerHTML=`<div class="page"><div class="card"><h2>Course could not load</h2><p class="muted">Walsall could not read the Naxosv2 course pack.</p><pre>${esc(e.stack||e)}</pre></div></div>`}}
async function loadCourse(key){const source=await fetch(SOURCE,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Could not load Naxos source');return r.json()});state.courses=Object.fromEntries(Object.entries(source.courses||{}).filter(([,v])=>v.type==='standard-main-packs'));const cfg=source.courses[key];if(!cfg)throw Error('Course not found in Naxosv2: '+key);if(cfg.type!=='standard-main-packs')throw Error('This learner build currently supports standard learner packs.');const packs=await fetch(NAXOS+'data/standards/'+key+'/main-packs.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Could not load '+key+' packs');return r.json()});state.course={key,config:cfg,metadata:packs};state.packs=packs.packs||[];state.profile.courseKey=key;save();$('#courseLabel').textContent=key+' · '+state.packs.length+' packs'}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));if(state.view==='home')renderHome();else if(state.view==='packs')renderPacks();else if(state.view==='otj')renderOTJ();else renderProfile()}
function renderHome(){const done=state.packs.filter(p=>pct(p)>=100).length,hours=state.otj.reduce((a,b)=>a+Number(b.hours||0),0);$('#app').innerHTML=`<div class="page"><section class="hero"><h1>${esc(state.profile.name||'Your evidence portfolio')}</h1><p>${esc(state.course?.key||'Course')} · ${done}/${state.packs.length} packs complete</p></section><div class="grid"><div class="card"><h3>Evidence packs</h3><strong>${done}/${state.packs.length}</strong><div class="progress"><i style="width:${state.packs.length?done/state.packs.length*100:0}%"></i></div><button class="btn primary full" onclick="go('packs')">Continue packs</button></div><div class="card"><h3>Off-the-job</h3><strong>${hours.toFixed(1)} hours</strong><p class="muted">${state.otj.length} entries</p><button class="btn full" onclick="go('otj')">Open OTJ</button></div></div><div class="card stack" style="margin-top:12px"><h3>Your course</h3><p class="muted">The packs shown here come directly from Naxosv2. Course content is not editable by learners.</p></div></div>`}
function renderPacks(){const html=state.packs.map((p,i)=>`<div class="card pack" onclick="openPack(${i})"><div class="pack-num">${String(i+1).padStart(2,'0')}</div><div style="flex:1"><h3>${esc(p.title)}</h3><p class="muted">${esc(p.summary)}</p><div class="status">${status(p)} · ${pct(p)}%</div><div class="progress"><i style="width:${pct(p)}%"></i></div></div></div>`).join('');$('#app').innerHTML=`<div class="page"><h1>Evidence packs</h1><p class="muted">Follow the Naxosv2 packs. Each pack tells you what evidence to collect.</p><div class="stack">${html}</div></div>`}

async function openPack(i){state.currentPack=i;save();const p=state.packs[i],e=state.evidence[p.id]||{photos:[],statement:'',signature:'',signedDate:''};const photos=await Promise.all(p.capture.map((_,n)=>photoGet(photoKey(p.id,n)).catch(()=>null)));const signed=e.signature?`<span class="status">Signed ${esc(e.signedDate||'')}</span>`:'';$('#app').innerHTML=`<div class="page"><button class="btn" onclick="go('packs')">← All packs</button><div class="card" style="margin-top:12px"><div class="status">PACK ${String(i+1).padStart(2,'0')}</div><h1>${esc(p.title)}</h1><p class="muted">${esc(p.summary)}</p><h3>Follow these photo prompts</h3><ul class="checklist">${p.capture.map((x,n)=>`<li><span class="${photos[n]?'tick':''}">${photos[n]?'✓':'○'}</span> ${esc(x)}</li>`).join('')}</ul></div><div class="card stack" style="margin-top:12px"><h3>Take your photos</h3><p class="muted">Take one clear photo for each prompt. Photos are saved on this device.</p><div class="photo-grid">${p.capture.map((prompt,n)=>photoBox(p.id,n,prompt,photos[n])).join('')}</div></div><div class="card stack" style="margin-top:12px"><h3>Your statement</h3><p class="muted">Explain what you did, how you did it and how you checked the finished work. Minimum 100 words.</p><textarea id="statement" placeholder="Write your statement here…" oninput="saveStatement('${p.id}',this.value)">${esc(e.statement||'')}</textarea><div class="status"><span id="wordCount">${wordCount(e.statement||'')}</span> words · minimum 100</div></div><div class="card stack" style="margin-top:12px"><h3>Mapped KSBs</h3><p class="muted">${(p.primaryKSBs||[]).map(esc).join(' · ')}</p></div><div class="card stack" style="margin-top:12px"><h3>Touchscreen signature</h3><p class="muted">Sign in the box below before downloading. The signature date will be recorded automatically as ${esc(nowUK())}.</p><div style="border:2px solid #cbd5d1;border-radius:14px;background:#fff;overflow:hidden;touch-action:none"><canvas id="signatureCanvas" width="900" height="280" style="display:block;width:100%;height:180px;touch-action:none"></canvas></div><div style="display:flex;gap:8px;align-items:center;margin-top:8px"><button class="btn" type="button" onclick="clearSignature()">Clear signature</button>${signed}</div></div><button class="btn green full" style="margin-top:12px" ${pct(p)<100?'disabled':''} onclick="downloadPack(${i})">Download completed pack PDF</button></div>`;initSignatureCanvas(e.signature||'')}
function photoBox(id,n,prompt,data){return `<div><label class="photo-box">${data?`<img src="${data}" alt="${esc(prompt)}"><button onclick="event.preventDefault();removePhoto('${id}',${n})">×</button>`:`<input type="file" accept="image/*" capture="environment" style="position:absolute;inset:0;opacity:0;cursor:pointer" onchange="addPhoto(event,'${id}',${n})"><div style="padding:18px;text-align:center"><strong>+ Photo</strong><div class="prompt">${esc(prompt)}</div></div>`}</label></div>`}
function saveStatement(id,v){state.evidence[id]=state.evidence[id]||{photos:[],statement:'',signature:'',signedDate:''};state.evidence[id].statement=v;save();const w=$('#wordCount');if(w)w.textContent=wordCount(v)}
async function addPhoto(ev,id,n){const file=ev.target.files?.[0];if(!file)return;try{const data=await resizeImage(file,1200);await photoPut(photoKey(id,n),data);state.evidence[id]=state.evidence[id]||{photos:[],statement:'',signature:'',signedDate:''};state.evidence[id].photos=state.evidence[id].photos||[];state.evidence[id].photos[n]={name:file.name};save();await openPack(state.currentPack)}catch(e){console.error(e);toast('Photo could not be saved')}}
async function removePhoto(id,n){const e=state.evidence[id];if(e?.photos)e.photos[n]=null;await photoDelete(photoKey(id,n));save();openPack(state.currentPack)}
function resizeImage(file,max){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const scale=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}

let signatureDrawing=false,signatureMoved=false,signatureCtx=null;
function initSignatureCanvas(saved){const c=$('#signatureCanvas');if(!c)return;signatureCtx=c.getContext('2d');signatureCtx.lineWidth=4;signatureCtx.lineCap='round';signatureCtx.lineJoin='round';signatureCtx.strokeStyle='#173f3a';if(saved){const im=new Image();im.onload=()=>signatureCtx.drawImage(im,0,0);im.src=saved}const point=e=>{const r=c.getBoundingClientRect();return {x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};const start=e=>{e.preventDefault();signatureDrawing=true;signatureMoved=false;const p=point(e);signatureCtx.beginPath();signatureCtx.moveTo(p.x,p.y)};const move=e=>{if(!signatureDrawing)return;e.preventDefault();signatureMoved=true;const p=point(e);signatureCtx.lineTo(p.x,p.y);signatureCtx.stroke()};const end=e=>{if(!signatureDrawing)return;e.preventDefault();signatureDrawing=false;if(signatureMoved)saveSignature()};c.onpointerdown=start;c.onpointermove=move;c.onpointerup=end;c.onpointercancel=end;c.onpointerleave=end}
function saveSignature(){const c=$('#signatureCanvas');if(!c)return;const data=c.toDataURL('image/png');state.evidence[state.packs[state.currentPack].id]=state.evidence[state.packs[state.currentPack].id]||{photos:[],statement:'',signature:'',signedDate:''};state.evidence[state.packs[state.currentPack].id].signature=data;state.evidence[state.packs[state.currentPack].id].signedDate=nowUK();save()}
function clearSignature(){const c=$('#signatureCanvas');if(!c)return;signatureCtx.clearRect(0,0,c.width,c.height);const id=state.packs[state.currentPack].id;state.evidence[id]=state.evidence[id]||{photos:[],statement:'',signature:'',signedDate:''};state.evidence[id].signature='';state.evidence[id].signedDate='';save();openPack(state.currentPack)}

function newPdf(){const {jsPDF}=window.jspdf;return new jsPDF({unit:'mm',format:'a4',compress:true})}
const PDF={left:12,right:12,top:12,bottom:12,width:186,pageH:297};
function writeWrapped(doc,text,x,y,width,line=4.5){const lines=doc.splitTextToSize(String(text||''),width);for(const lineText of lines){doc.text(lineText,x,y);y+=line}return y}
function footer(doc,page){doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text('Walsall Evidence',PDF.left,PDF.pageH-6);doc.text(`Page ${page} of 2`,PDF.pageH-PDF.right,PDF.pageH-6,{align:'right'})}
function addImageFit(doc,data,x,y,maxW,maxH){const props=doc.getImageProperties(data);const ratio=Math.min(maxW/props.width,maxH/props.height);const w=props.width*ratio,h=props.height*ratio;doc.addImage(data,'JPEG',x+(maxW-w)/2,y+(maxH-h)/2,w,h);return {w,h}}
function drawPhotoPage(doc,p,photos){doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Evidence Pack',PDF.left,PDF.top+3);doc.setFontSize(11);doc.setFont('helvetica','normal');doc.text(p.title,PDF.left,PDF.top+10);doc.setFontSize(8);doc.text(`Learner: ${state.profile.name||'Not entered'}   Course: ${state.profile.courseKey}   Date: ${nowUK()}`,PDF.left,PDF.top+16);const gap=4;const gridTop=PDF.top+22;const gridBottom=PDF.pageH-PDF.bottom-8;const cellW=(PDF.width-gap*2)/3;const cellH=(gridBottom-gridTop-gap)/2;for(let n=0;n<6;n++){const col=n%3,row=Math.floor(n/3),x=PDF.left+col*(cellW+gap),y=gridTop+row*(cellH+gap);doc.setDrawColor(190);doc.rect(x,y,cellW,cellH);if(photos[n]){addImageFit(doc,photos[n],x+1,y+1,cellW-2,cellH-2)}else{doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Photo missing',x+cellW/2,y+cellH/2,{align:'center'})}doc.setFont('helvetica','bold');doc.setFontSize(7);doc.text(`${n+1}. ${String(p.capture[n]||'Photo').slice(0,45)}`,x+2,y+cellH-3)}footer(doc,1)}
function drawDetailsPage(doc,p,e){doc.addPage();doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Evidence Details',PDF.left,PDF.top+3);let y=PDF.top+12;doc.setFont('helvetica','normal');doc.setFontSize(9);y=writeWrapped(doc,`Learner: ${state.profile.name||'Not entered'}`,PDF.left,y,PDF.width);y=writeWrapped(doc,`Course: ${state.profile.courseKey}`,PDF.left,y,PDF.width);y=writeWrapped(doc,`Evidence pack: ${p.title}`,PDF.left,y,PDF.width);y=writeWrapped(doc,`Completed/signed date: ${e.signedDate||nowUK()}`,PDF.left,y,PDF.width);y+=4;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Photo details',PDF.left,y);y+=6;doc.setFont('helvetica','normal');doc.setFontSize(8);for(let n=0;n<6;n++){y=writeWrapped(doc,`${n+1}. ${p.capture[n]||'Photo'}`,PDF.left,y,PDF.width,3.8)}y+=3;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('Learner statement',PDF.left,y);y+=5;doc.setFont('helvetica','normal');doc.setFontSize(8);y=writeWrapped(doc,e.statement,PDF.left,y,PDF.width,3.8);y+=4;doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Mapped KSBs',PDF.left,y);y+=4;doc.setFont('helvetica','normal');doc.setFontSize(8);y=writeWrapped(doc,(p.primaryKSBs||[]).join(' · ')||'None recorded',PDF.left,y,PDF.width,3.8);y+=5;doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Learner signature',PDF.left,y);y+=3;if(e.signature)doc.addImage(e.signature,'PNG',PDF.left,y,70,22);y+=25;doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(`Signed electronically on ${e.signedDate||nowUK()}`,PDF.left,y);footer(doc,2)}
async function downloadPack(i){const p=state.packs[i],e=state.evidence[p.id]||{};if(pct(p)<100){toast('Complete the photos and statement first');return}if(!e.signature){toast('Please sign the touchscreen signature box before downloading');return}const photos=await Promise.all(p.capture.slice(0,6).map((_,n)=>photoGet(photoKey(p.id,n))));if(photos.length<6||photos.some(x=>!x)){toast('All 6 photos are required before downloading');return}const doc=newPdf();drawPhotoPage(doc,p,photos);drawDetailsPage(doc,p,e);const safe=(p.title||'evidence-pack').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();doc.save(`walsall-${safe}-${formatUKDate(e.signedDate||todayISO()).replaceAll('/','-')}.pdf`)}

function renderOTJ(){const total=state.otj.reduce((a,b)=>a+Number(b.hours||0),0),rows=state.otj.map((x,i)=>`<div class="card"><div style="display:flex;justify-content:space-between"><strong>${formatUKDate(x.date)}</strong><strong>${Number(x.hours).toFixed(1)}h</strong></div><p>${esc(x.activity)}</p><p class="muted">${esc(x.learning)}</p><button class="btn" onclick="deleteOTJ(${i})">Delete</button></div>`).join('');$('#app').innerHTML=`<div class="page"><div class="hero"><h1>Off-the-job training</h1><p>${total.toFixed(1)} hours recorded</p></div><div class="card stack"><h3>Add OTJ entry</h3><input class="input" id="otjDate" type="date" value="${todayISO()}"><input class="input" id="otjHours" type="number" min="0.25" step="0.25" placeholder="Hours"><input class="input" id="otjActivity" placeholder="What did you do?"><textarea id="otjLearning" placeholder="What did you learn?"></textarea><button class="btn primary full" onclick="addOTJ()">Save OTJ entry</button></div><div class="stack" style="margin-top:12px">${rows||'<div class="card muted">No OTJ entries yet.</div>'}</div><button class="btn green full" style="margin-top:12px" ${state.otj.length?'':'disabled'} onclick="downloadOTJ()">Download collated OTJ PDF</button></div>`}
function addOTJ(){const date=$('#otjDate').value,hours=Number($('#otjHours').value),activity=$('#otjActivity').value.trim(),learning=$('#otjLearning').value.trim();if(!date||!hours||!activity){toast('Enter date, hours and activity');return}state.otj.push({date,hours,activity,learning});state.otj.sort((a,b)=>a.date.localeCompare(b.date));save();renderOTJ();toast('OTJ entry saved')}
function deleteOTJ(i){state.otj.splice(i,1);save();renderOTJ()}
function downloadOTJ(){const doc=newPdf();doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Off-the-job Training Record',PDF.left,PDF.top+3);let y=PDF.top+13;doc.setFont('helvetica','normal');doc.setFontSize(9);y=writeWrapped(doc,`Learner: ${state.profile.name||'Not entered'}`,PDF.left,y,PDF.width);y=writeWrapped(doc,`Course: ${state.profile.courseKey}`,PDF.left,y,PDF.width);y+=4;state.otj.forEach((x,i)=>{if(y>PDF.pageH-25){footer(doc,doc.getNumberOfPages());doc.addPage();y=PDF.top}doc.setFont('helvetica','bold');doc.text(`${i+1}. ${formatUKDate(x.date)} · ${Number(x.hours).toFixed(1)} hours`,PDF.left,y);y+=4;doc.setFont('helvetica','normal');y=writeWrapped(doc,x.activity,PDF.left,y,PDF.width,3.8);if(x.learning)y=writeWrapped(doc,'Learning: '+x.learning,PDF.left,y,PDF.width,3.8);y+=3});doc.setFont('helvetica','bold');doc.text(`Total: ${state.otj.reduce((a,b)=>a+Number(b.hours||0),0).toFixed(1)} hours`,PDF.left,y+3);footer(doc,doc.getNumberOfPages());doc.save(`walsall-off-the-job-${nowUK().replaceAll('/','-')}.pdf`)}
function renderProfile(){const opts=Object.keys(state.courses).map(k=>`<option value="${esc(k)}" ${k===state.profile.courseKey?'selected':''}>${esc(k)}</option>`).join('');$('#app').innerHTML=`<div class="page"><div class="card stack"><h1>Profile</h1><label>Name<input class="input" id="name" value="${esc(state.profile.name)}" placeholder="Your name"></label><label>Course<select class="input" id="course">${opts}</select></label><button class="btn primary full" onclick="saveProfile()">Save profile</button><p class="muted">Course packs are read directly from Naxosv2. Learners can select their assigned course, but cannot change its pack content.</p></div></div>`}
async function saveProfile(){const newKey=$('#course').value;state.profile.name=$('#name').value.trim();if(newKey!==state.profile.courseKey){try{await loadCourse(newKey)}catch(e){toast(e.message);return}}save();renderHome();toast('Profile saved')}
function go(v){state.view=v;render()}
function toast(message){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText='position:fixed;left:50%;bottom:78px;transform:translateX(-50%);background:#173f3a;color:#fff;padding:10px 14px;border-radius:12px;z-index:9999;font-size:14px;max-width:90%;text-align:center';document.body.appendChild(t)}t.textContent=message;t.style.display='block';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.display='none',2600)}
document.addEventListener('DOMContentLoaded',load);
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
