'use strict';
(function(){
  const style=document.createElement('style');
  style.textContent=`
    .confidence-card{margin-top:12px}.confidence-overall{text-align:center;padding:8px 0 16px}.confidence-score{font-size:42px;line-height:1;font-weight:850;letter-spacing:-1.5px;color:var(--green-dark)}.confidence-label{margin-top:5px;font-size:12px;color:var(--muted);font-weight:700}.confidence-list{display:grid;gap:8px}.confidence-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 12px;border:1px solid var(--line);border-radius:13px;background:#fbfcfb;min-width:0}.confidence-name{font-weight:700;line-height:1.25;min-width:0;overflow-wrap:anywhere}.confidence-select{width:76px;min-height:40px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--text);font-weight:800;padding:0 8px;flex:0 0 76px}@media(max-width:420px){.confidence-row{padding:10px}.confidence-select{width:70px;flex-basis:70px}}
  `;
  document.head.appendChild(style);
  function ratings(){state.confidence=state.confidence||{};return state.packs.map((p,i)=>({p,i,value:Number(state.confidence[p.id]||0)}))}
  function overall(){const r=ratings().filter(x=>x.value>=1);return r.length?Math.round(r.reduce((a,x)=>a+x.value,0)/r.length/5*100):0}
  function renderConfidenceHome(){if(state.view!=='home'||!state.packs.length)return;const html=`<section class="card confidence-card" id="confidenceSection"><div class="confidence-overall"><div class="confidence-score" id="overallConfidence">${overall()}%</div><div class="confidence-label">Overall confidence</div></div><div class="confidence-list">${ratings().map(({p,i,value})=>`<label class="confidence-row"><span class="confidence-name">${esc(p.title)}</span><select class="confidence-select" aria-label="Confidence for ${esc(p.title)}" onchange="setConfidence(${i},this.value)"><option value="0" ${value===0?'selected':''}>Select</option><option value="1" ${value===1?'selected':''}>1 / 5</option><option value="2" ${value===2?'selected':''}>2 / 5</option><option value="3" ${value===3?'selected':''}>3 / 5</option><option value="4" ${value===4?'selected':''}>4 / 5</option><option value="5" ${value===5?'selected':''}>5 / 5</option></select></label>`).join('')}</div></section>`;const existing=document.getElementById('confidenceSection');if(existing)existing.outerHTML=html;else $('#app').querySelector('.page')?.insertAdjacentHTML('beforeend',html)}
  window.setConfidence=function(i,value){state.confidence=state.confidence||{};const p=state.packs[i];if(!p)return;const v=Number(value)||0;if(v)state.confidence[p.id]=v;else delete state.confidence[p.id];save();const score=$('#overallConfidence');if(score)score.textContent=overall()+'%'};
  document.addEventListener('click',e=>{const home=e.target.closest('.bottom-nav button[data-view="home"]');if(home)setTimeout(renderConfidenceHome,20)});
  let tries=0;const timer=setInterval(()=>{tries++;if(state.packs?.length){renderConfidenceHome();if(state.view==='home'||tries>20)clearInterval(timer)}if(tries>40)clearInterval(timer)},100);
})();